### ISSUE TITLE
Task manager

### ISSUE THREAD

**Issue by afilipov1** [TeamMimosa-Telerik/Mimosa#1]
# TODO List
- [x] distribute tasks
- [x] make app structure
- [x] run server  
- [x] create separated branches
- [x] create front-end branch
- [x] import dependencies with System.js
- [x] make routing
- [x] make page responsive
- [x] use session storage for points
- [x] deploy on heroku
- [x] integrate facebook api for sharing 
- [x] ajax with jQuery
- [x] ajax from localhost
- [x] code refactoring (Antonio and Aleks) 
- [ ] writing tests
