### ISSUE TITLE
TODO: Design

### ISSUE THREAD

**Issue by afilipov1** [TeamMimosa-Telerik/Mimosa#12]
- [x] страниците да нямат вертикален и хоризонтален скрол
- [x] има проблем с responsive на category page (при ~800px)
- [x] след като се отговорят въпросите от категорията трябва като се unlock-не баджа
- [x] в баджовете да се слажат нинджите от category page(защото в момента не носят много смъсъл)
- [x] баджовете да са кръгли, по-големи със звездичка в тях
- [x] в category page да се заключват категориите (за да можем да изберем следваща категория, трябва да сме отключили предишната). Нека първоначално само първата да е с removeClass(''blured');
- [x] jquery text-fill за дългите отговори
- [x] signout от страницата  с въпросите
